services:
  nginx:
    image: nginx:alpine
    container_name: proxy-nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - red_interna

  servidor-bd:
    image: mysql:8.0
    container_name: mysql_produccion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sena123
      MYSQL_DATABASE: adso_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_interna


  web:
    image: 616yuuki/mi-app-python:v1
    container_name: app_produccion
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - servidor-bd
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge
volumes:
  db_data: