services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports: 
      - "80:80" #Http
      - "81:81" #Administracion de la API
      - "443:443" #Https
    volumes:
      - ./npm_data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - red_interna

  servidor-bd:
    image: mysql:8.0
    container_name: mysql_produccion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sena123
      MYSQL_DATABASE: adso_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_interna


  web:
    build: .
    image: 616yuuki/mi-app-python:latest
    container_name: app_produccion
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - servidor-bd
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge
volumes:
  db_data: